# JVM & Style
org.gradle.jvmargs=-Xmx1536m
kotlin.code.style=official
# Modern Android Standards
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
# Crucial AGP 9.2+ Configurations
android.newDsl=true
android.builtInKotlin=true
android.r8.strictFullModeForKeepRules=true