[versions]
## SDK Versions
compileSdk = "37"
minSdk = "26"
targetSdk = "37"

## App Versions
major = "1"
minor = "0"
hotfix = "1"

## Gradle
androidGradlePlugin = "9.2.1"
hilt = "2.60"
kotlin = "2.4.0"
ksp = "2.3.9"
safeargs = "2.9.8"

# Dependencies
androidXAppCompat = "1.7.1"
androidXConstraintLayout = "2.2.1"
androidXCore = "1.19.0"
androidXFragment = "1.8.9"
androidXNavigation = "2.9.8"
androidXRecyclerView = "1.4.0"
glide = "5.0.7"
gson = "2.14.0"
kotlinX = "1.11.0"
material = "1.14.0"
taptargetview = "1.15.0"

espresso = "3.7.0"
junit = "4.13.2"
runner = "1.7.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidXAppCompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidXConstraintLayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidXCore" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidXFragment" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidXNavigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidXNavigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidXRecyclerView" }

androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

junit = { module = "junit:junit", version.ref = "junit" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinX" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinX" }

material = { module = "com.google.android.material:material", version.ref = "material" }

taptargetview = { module = "com.getkeepsafe.taptargetview:taptargetview", version.ref = "taptargetview" }

[plugins]
android-gradle = { id = "com.android.application", version.ref = "androidGradlePlugin" }

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "safeargs" }

[bundles]
## add bundled up libs here eg.
# app-ui = [
#     "compose-compiler",
#     "androidx-core",
#     "androidx-lifecycle-runtime",
#     "androidx-lifecycle-viewmodel",
#     "androidx-lifecycle-compose",
#     "compose-ui",
#     "compose-tooling",
#     "compose-foundation",
#     "compose-material",
#     "compose-activity"
# ]